{% set name = "ecoinvent_interface" %}
{% set version = "3.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ecoinvent_interface-{{ version }}.tar.gz
  sha256: 5a54a774532b3ecc562148e0a75e1f375d2e023efd2215bdbf7c4e93a4b95b47

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=68.0
    - pip
  run:
    - python >={{ python_min }}
    - lxml
    - platformdirs
    - py7zr
    - pydantic-settings
    - pyecospold
    - requests
    - tqdm

test:
  imports:
    - ecoinvent_interface
  # Removing for now as upstream pyecospold is broken. Shouldn't stop this release.
  # commands:
  #   - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/brightway-lca/ecoinvent_interface/
  summary: Unofficial client for interfacing with ecoinvent database
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cmutel
