{% set name = "ecoinvent_interface" %}
{% set version = "2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ecoinvent_interface-{{ version }}.tar.gz
  sha256: 12cea215b9ad59312f88912b1d80abda16246cbebf1c295675e397349a1e1310

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=68.0
    - pip
  run:
    - python >=3.9
    - lxml
    - platformdirs
    - py7zr
    - pydantic-settings
    - pyecospold
    - requests
    - tqdm

test:
  imports:
    - ecoinvent_interface
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/brightway-lca/ecoinvent_interface/
  summary: Unofficial client for interfacing with ecoinvent database
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cmutel
